// lib/furniture-data.ts
// This is your inventory database. Right now it's hardcoded — later you'll
// replace this with a real database (Supabase/Postgres) or scrape vendor APIs.
// For now, 25 realistic items across Delhi NCR and All India.

import { FurnitureItem } from './types'

export const furnitureData: FurnitureItem[] = [

  // ━━ SOFAS ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  {
    id: 'pf_s001',
    name: 'Como 3-Seater Fabric Sofa',
    category: 'sofa',
    price: 18999,
    brand: 'Pepperfry',
    cities: ['All India'],
    deliveryAvailable: true,
    style: ['modern', 'minimal'],
    material: 'Polyester Fabric',
    dimensions: { width: 200, depth: 84, height: 83 },
    durability: 'medium',
    maintenanceEase: 'medium',
    imageUrl: '',
    productUrl: 'https://www.pepperfry.com/product/como-3-seater-sofa',
    inStock: true,
    rating: 4.2,
    reviewCount: 1240,
    description:
      'Sleek 3-seater with clean lines. Available in 6 colours including grey, teal, and mustard. Easy self-assembly.',
    tags: ['3-seater', 'compact', 'colorful', 'easy-assembly'],
  },

  {
    id: 'ul_s001',
    name: 'Cloud Sectional Sofa',
    category: 'sofa',
    price: 38999,
    brand: 'Urban Ladder',
    cities: ['Delhi NCR', 'Mumbai', 'Bengaluru', 'Hyderabad', 'Chennai', 'Pune'],
    deliveryAvailable: true,
    style: ['warm', 'modern'],
    material: 'Premium Velvet',
    dimensions: { width: 260, depth: 160, height: 85 },
    durability: 'medium',
    maintenanceEase: 'low',
    imageUrl: '',
    productUrl: 'https://www.urbanladder.com/products/cloud-sectional-sofa',
    inStock: true,
    rating: 4.5,
    reviewCount: 623,
    description:
      'L-shaped sectional in plush velvet. Deep seats ideal for large living rooms. Dry clean recommended.',
    tags: ['L-shaped', 'sectional', 'velvet', 'large-room', 'premium'],
  },

  {
    id: 'ikea_s001',
    name: 'EKTORP 3-Seat Sofa',
    category: 'sofa',
    price: 31990,
    brand: 'IKEA',
    cities: ['Delhi NCR', 'Mumbai', 'Hyderabad', 'Bengaluru'],
    deliveryAvailable: true,
    style: ['minimal', 'warm'],
    material: 'Cotton Fabric (removable, washable cover)',
    dimensions: { width: 218, depth: 88, height: 88 },
    durability: 'high',
    maintenanceEase: 'high',
    imageUrl: '',
    productUrl: 'https://www.ikea.com/in/en/p/ektorp-3-seat-sofa',
    inStock: true,
    rating: 4.4,
    reviewCount: 2100,
    description:
      'Iconic comfort with machine-washable, interchangeable covers. Outstanding for families with kids or pets. 10-year frame warranty.',
    tags: ['washable', 'kid-friendly', 'pet-friendly', 'durable', 'replaceable-cover', 'warranty'],
  },

  {
    id: 'kn_s001',
    name: 'Sheesham Wood Sofa Set (3+1+1)',
    category: 'sofa',
    price: 27500,
    brand: 'Kirti Nagar Furniture',
    cities: ['Delhi NCR'],
    deliveryAvailable: false,
    style: ['traditional', 'warm'],
    material: 'Solid Sheesham Wood + Cushions',
    dimensions: { width: 180, depth: 75, height: 90 },
    durability: 'high',
    maintenanceEase: 'medium',
    imageUrl: '',
    productUrl: '',
    inStock: true,
    rating: 4.1,
    reviewCount: 45,
    description:
      'Solid sheesham frame with thick cushions. Traditional Indian craftsmanship built to last decades. In-store pickup only from Kirti Nagar market, Delhi.',
    tags: ['solid-wood', 'traditional', 'local-store', 'artisan', '3-1-1-set'],
  },

  {
    id: 'nl_s001',
    name: 'Gracia 2-Seater Sofa',
    category: 'sofa',
    price: 9499,
    brand: 'Nilkamal',
    cities: ['All India'],
    deliveryAvailable: true,
    style: ['modern', 'minimal'],
    material: 'Leatherette',
    dimensions: { width: 155, depth: 78, height: 82 },
    durability: 'medium',
    maintenanceEase: 'high',
    imageUrl: '',
    productUrl: 'https://www.nilkamal.com/gracia-sofa',
    inStock: true,
    rating: 3.9,
    reviewCount: 3450,
    description:
      'Budget-friendly 2-seater in wipe-clean leatherette. Ideal for small apartments and rental homes.',
    tags: ['budget', '2-seater', 'leatherette', 'compact', 'easy-clean', 'rental-friendly'],
  },

  {
    id: 'du_s001',
    name: 'Luxe Electric Recliner Sofa',
    category: 'sofa',
    price: 89000,
    brand: 'Durian',
    cities: ['Delhi NCR', 'Mumbai', 'Bengaluru', 'Hyderabad'],
    deliveryAvailable: true,
    style: ['modern', 'industrial'],
    material: 'Full-grain Leather',
    dimensions: { width: 230, depth: 95, height: 100 },
    durability: 'high',
    maintenanceEase: 'medium',
    imageUrl: '',
    productUrl: 'https://www.durian.in/luxe-recliner',
    inStock: true,
    rating: 4.6,
    reviewCount: 214,
    description:
      'Premium electric recliner in full-grain leather. USB charging ports, cup holders, memory foam seats.',
    tags: ['recliner', 'leather', 'premium', 'electric', 'luxury', 'usb'],
  },

  {
    id: 'fb_s001',
    name: 'Rajwada Handcrafted Sofa',
    category: 'sofa',
    price: 52000,
    brand: 'FabIndia',
    cities: ['All India'],
    deliveryAvailable: true,
    style: ['traditional', 'eclectic'],
    material: 'Handloom Fabric + Mango Wood',
    dimensions: { width: 195, depth: 80, height: 88 },
    durability: 'high',
    maintenanceEase: 'low',
    imageUrl: '',
    productUrl: 'https://www.fabindia.com/rajwada-sofa',
    inStock: true,
    rating: 4.3,
    reviewCount: 187,
    description:
      'Artisanal sofa with block-print handloom upholstery and solid mango wood frame. Each piece is unique.',
    tags: ['artisan', 'handloom', 'mango-wood', 'traditional', 'unique', 'block-print'],
  },

  {
    id: 'gi_s001',
    name: 'Slumber 3-Seater Sofa Cum Bed',
    category: 'sofa',
    price: 24500,
    brand: 'Godrej Interio',
    cities: ['All India'],
    deliveryAvailable: true,
    style: ['modern', 'minimal'],
    material: 'Fabric',
    dimensions: { width: 205, depth: 90, height: 85 },
    durability: 'high',
    maintenanceEase: 'medium',
    imageUrl: '',
    productUrl: 'https://www.godrejinterio.com/slumber-sofa-bed',
    inStock: true,
    rating: 4.1,
    reviewCount: 892,
    description:
      'Converts from sofa to full bed. Perfect for guest rooms or studio apartments. Godrej 5-year warranty.',
    tags: ['sofa-bed', 'guest-room', 'convertible', 'warranty', 'space-saving'],
  },

  {
    id: 'wo_s001',
    name: 'Acacia 2-Seater Loveseat',
    category: 'sofa',
    price: 14999,
    brand: 'Wooden Street',
    cities: ['All India'],
    deliveryAvailable: true,
    style: ['warm', 'minimal'],
    material: 'Sheesham Wood + Fabric',
    dimensions: { width: 145, depth: 75, height: 87 },
    durability: 'high',
    maintenanceEase: 'medium',
    imageUrl: '',
    productUrl: 'https://www.woodenstreet.com/acacia-loveseat',
    inStock: true,
    rating: 4.3,
    reviewCount: 729,
    description:
      'Compact loveseat with solid sheesham frame and removable cushion covers. Ideal for small apartments.',
    tags: ['2-seater', 'loveseat', 'sheesham', 'compact', 'solid-wood', 'removable-covers'],
  },

  // ━━ BEDS ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  {
    id: 'pf_b001',
    name: 'Hosta Queen Bed with Hydraulic Storage',
    category: 'bed',
    price: 22999,
    brand: 'Pepperfry',
    cities: ['All India'],
    deliveryAvailable: true,
    style: ['modern', 'minimal'],
    material: 'Engineered Wood',
    dimensions: { width: 165, depth: 205, height: 90 },
    durability: 'medium',
    maintenanceEase: 'high',
    imageUrl: '',
    productUrl: 'https://www.pepperfry.com/hosta-queen-bed',
    inStock: true,
    rating: 4.1,
    reviewCount: 1820,
    description:
      'Queen-size bed with hydraulic storage lift underneath. 4 colour options. Fits standard queen mattress (60"x78").',
    tags: ['queen', 'storage', 'hydraulic', 'space-saving', 'engineered-wood'],
  },

  {
    id: 'ul_b001',
    name: 'Hendrix Solid Wood King Bed',
    category: 'bed',
    price: 38500,
    brand: 'Urban Ladder',
    cities: ['Delhi NCR', 'Mumbai', 'Bengaluru', 'Hyderabad', 'Chennai', 'Pune'],
    deliveryAvailable: true,
    style: ['warm', 'modern'],
    material: 'Solid Acacia Wood',
    dimensions: { width: 190, depth: 215, height: 105 },
    durability: 'high',
    maintenanceEase: 'medium',
    imageUrl: '',
    productUrl: 'https://www.urbanladder.com/hendrix-king-bed',
    inStock: true,
    rating: 4.5,
    reviewCount: 412,
    description:
      'Solid acacia king bed with upholstered headboard. Natural grain, rich warm finish. Fits 72"x78" mattress.',
    tags: ['king', 'solid-wood', 'acacia', 'upholstered-headboard', 'premium'],
  },

  {
    id: 'gi_b001',
    name: 'Single Bed with Pull-out Trundle',
    category: 'bed',
    price: 18000,
    brand: 'Godrej Interio',
    cities: ['All India'],
    deliveryAvailable: true,
    style: ['modern', 'minimal'],
    material: 'Steel + MDF',
    dimensions: { width: 100, depth: 200, height: 80 },
    durability: 'high',
    maintenanceEase: 'high',
    imageUrl: '',
    productUrl: 'https://www.godrejinterio.com/trundle-single-bed',
    inStock: true,
    rating: 4.2,
    reviewCount: 567,
    description:
      'Single bed with pull-out trundle. One bed becomes two — ideal for kids rooms or small guest rooms.',
    tags: ['single', 'trundle', 'kids', 'guest', 'space-saving', 'steel-frame'],
  },

  // ━━ DINING TABLES ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  {
    id: 'ikea_d001',
    name: 'EKEDALEN Extendable Dining Table',
    category: 'dining-table',
    price: 19990,
    brand: 'IKEA',
    cities: ['Delhi NCR', 'Mumbai', 'Hyderabad', 'Bengaluru'],
    deliveryAvailable: true,
    style: ['minimal', 'modern'],
    material: 'Oak Veneer + Solid Wood Legs',
    dimensions: { width: 120, depth: 80, height: 75 },
    durability: 'medium',
    maintenanceEase: 'high',
    imageUrl: '',
    productUrl: 'https://www.ikea.com/in/en/p/ekedalen-extendable-table',
    inStock: true,
    rating: 4.3,
    reviewCount: 890,
    description:
      'Extends from 4 to 6 seats. Space-saving, versatile. Oak veneer top, solid wood legs.',
    tags: ['extendable', '4-to-6-seater', 'oak', 'space-saving'],
  },

  {
    id: 'pf_d001',
    name: 'Ariel 6-Seater Glass Dining Set',
    category: 'dining-table',
    price: 29999,
    brand: 'Pepperfry',
    cities: ['All India'],
    deliveryAvailable: true,
    style: ['modern', 'minimal'],
    material: 'Tempered Glass + Metal',
    dimensions: { width: 150, depth: 90, height: 76 },
    durability: 'medium',
    maintenanceEase: 'high',
    imageUrl: '',
    productUrl: 'https://www.pepperfry.com/ariel-dining-set',
    inStock: true,
    rating: 4.0,
    reviewCount: 645,
    description:
      '6-seater set with tempered glass top, metal frame. Chairs included. Very easy to wipe clean.',
    tags: ['6-seater', 'glass-top', 'metal', 'with-chairs', 'easy-clean'],
  },

  {
    id: 'ws_d001',
    name: 'Timor Solid Sheesham 4-Seater Table',
    category: 'dining-table',
    price: 21000,
    brand: 'Wooden Street',
    cities: ['All India'],
    deliveryAvailable: true,
    style: ['traditional', 'warm'],
    material: 'Solid Sheesham Wood',
    dimensions: { width: 120, depth: 75, height: 76 },
    durability: 'high',
    maintenanceEase: 'medium',
    imageUrl: '',
    productUrl: 'https://www.woodenstreet.com/timor-dining-table',
    inStock: true,
    rating: 4.4,
    reviewCount: 330,
    description:
      'Solid sheesham 4-seater with natural grain finish. No paint or veneer. Chairs sold separately.',
    tags: ['4-seater', 'solid-sheesham', 'natural', 'traditional', 'durable'],
  },

  // ━━ STUDY TABLES ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  {
    id: 'ikea_st001',
    name: 'LINNMON / ADILS Desk',
    category: 'study-table',
    price: 4999,
    brand: 'IKEA',
    cities: ['Delhi NCR', 'Mumbai', 'Hyderabad', 'Bengaluru'],
    deliveryAvailable: true,
    style: ['minimal', 'modern'],
    material: 'Particleboard + Metal Legs',
    dimensions: { width: 120, depth: 60, height: 74 },
    durability: 'low',
    maintenanceEase: 'high',
    imageUrl: '',
    productUrl: 'https://www.ikea.com/in/en/p/linnmon-adils-table',
    inStock: true,
    rating: 4.0,
    reviewCount: 4200,
    description:
      "India's most popular budget desk. Multiple colour options. Simple, functional, fast assembly.",
    tags: ['budget', 'wfh', 'simple', 'lightweight', 'desk'],
  },

  {
    id: 'pf_st001',
    name: 'Apex L-Shaped Computer Desk',
    category: 'study-table',
    price: 14999,
    brand: 'Pepperfry',
    cities: ['All India'],
    deliveryAvailable: true,
    style: ['modern', 'industrial'],
    material: 'MDF + Metal Frame',
    dimensions: { width: 140, depth: 120, height: 75 },
    durability: 'medium',
    maintenanceEase: 'high',
    imageUrl: '',
    productUrl: 'https://www.pepperfry.com/apex-l-desk',
    inStock: true,
    rating: 4.2,
    reviewCount: 780,
    description:
      'L-shaped WFH desk with monitor riser, cable management tray, and 2 built-in USB ports.',
    tags: ['L-shaped', 'wfh', 'cable-management', 'usb', 'monitor-riser'],
  },

  // ━━ CHAIRS ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  {
    id: 'ikea_c001',
    name: 'MARKUS Ergonomic Office Chair',
    category: 'chair',
    price: 19990,
    brand: 'IKEA',
    cities: ['Delhi NCR', 'Mumbai', 'Hyderabad', 'Bengaluru'],
    deliveryAvailable: true,
    style: ['modern', 'minimal'],
    material: 'Mesh Back + Fabric Seat',
    dimensions: { width: 67, depth: 65, height: 130 },
    durability: 'high',
    maintenanceEase: 'high',
    imageUrl: '',
    productUrl: 'https://www.ikea.com/in/en/p/markus-office-chair',
    inStock: true,
    rating: 4.5,
    reviewCount: 3100,
    description:
      'Ergonomic mesh back, adjustable lumbar support, adjustable armrests. Most popular WFH chair in India.',
    tags: ['ergonomic', 'mesh', 'wfh', 'lumbar', 'adjustable', 'office-chair'],
  },

  {
    id: 'pf_c001',
    name: 'Accent Velvet Armchair',
    category: 'chair',
    price: 12999,
    brand: 'Pepperfry',
    cities: ['All India'],
    deliveryAvailable: true,
    style: ['warm', 'eclectic'],
    material: 'Velvet + Solid Wood Legs',
    dimensions: { width: 75, depth: 78, height: 85 },
    durability: 'medium',
    maintenanceEase: 'low',
    imageUrl: '',
    productUrl: 'https://www.pepperfry.com/accent-velvet-chair',
    inStock: true,
    rating: 4.3,
    reviewCount: 421,
    description:
      'Statement accent chair in plush velvet. Available in Teal, Mustard, Blush, and Navy. Walnut-finish legs.',
    tags: ['accent', 'velvet', 'statement', 'colorful', 'armchair'],
  },

  // ━━ WARDROBES ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  {
    id: 'ikea_w001',
    name: 'PAX Wardrobe with Sliding Mirror Doors',
    category: 'wardrobe',
    price: 24990,
    brand: 'IKEA',
    cities: ['Delhi NCR', 'Mumbai', 'Hyderabad', 'Bengaluru'],
    deliveryAvailable: true,
    style: ['minimal', 'modern'],
    material: 'Particleboard + Mirror Glass',
    dimensions: { width: 150, depth: 60, height: 201 },
    durability: 'medium',
    maintenanceEase: 'high',
    imageUrl: '',
    productUrl: 'https://www.ikea.com/in/en/p/pax-wardrobe',
    inStock: true,
    rating: 4.3,
    reviewCount: 1560,
    description:
      'Modular wardrobe system with mirrored sliding doors. Fully customizable interior fittings. 10-year warranty.',
    tags: ['modular', 'mirror', 'customizable', 'sliding-doors', 'wardrobe'],
  },

  {
    id: 'gi_w001',
    name: 'Forte 3-Door Steel Wardrobe',
    category: 'wardrobe',
    price: 32000,
    brand: 'Godrej Interio',
    cities: ['All India'],
    deliveryAvailable: true,
    style: ['modern', 'minimal'],
    material: 'Cold-rolled Steel',
    dimensions: { width: 135, depth: 48, height: 185 },
    durability: 'high',
    maintenanceEase: 'high',
    imageUrl: '',
    productUrl: 'https://www.godrejinterio.com/forte-wardrobe',
    inStock: true,
    rating: 4.4,
    reviewCount: 2100,
    description:
      'Termite-proof, moisture-resistant steel wardrobe. Ideal for humid Indian climates. Godrej lifetime quality.',
    tags: ['steel', 'termite-proof', 'moisture-resistant', 'durable', 'lifetime'],
  },

  // ━━ COFFEE TABLES ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  {
    id: 'pf_ct001',
    name: 'Mesa Mango Wood Coffee Table',
    category: 'coffee-table',
    price: 8999,
    brand: 'Pepperfry',
    cities: ['All India'],
    deliveryAvailable: true,
    style: ['warm', 'minimal'],
    material: 'Solid Mango Wood',
    dimensions: { width: 110, depth: 60, height: 45 },
    durability: 'high',
    maintenanceEase: 'medium',
    imageUrl: '',
    productUrl: 'https://www.pepperfry.com/mesa-coffee-table',
    inStock: true,
    rating: 4.4,
    reviewCount: 893,
    description:
      'Natural mango wood with hairpin metal legs. Each piece has unique grain patterns. Pairs with any sofa style.',
    tags: ['mango-wood', 'hairpin-legs', 'natural', 'versatile', 'unique-grain'],
  },

  {
    id: 'ikea_ct001',
    name: 'VITTSJÖ Laptop Table / Coffee Table',
    category: 'coffee-table',
    price: 3490,
    brand: 'IKEA',
    cities: ['Delhi NCR', 'Mumbai', 'Hyderabad', 'Bengaluru'],
    deliveryAvailable: true,
    style: ['minimal', 'modern', 'industrial'],
    material: 'Tempered Glass + Steel',
    dimensions: { width: 100, depth: 36, height: 45 },
    durability: 'medium',
    maintenanceEase: 'high',
    imageUrl: '',
    productUrl: 'https://www.ikea.com/in/en/p/vittsjo-laptop-table',
    inStock: true,
    rating: 4.2,
    reviewCount: 2300,
    description:
      'Slim glass and steel table works as coffee table or laptop stand. Industrial look, budget price.',
    tags: ['budget', 'glass', 'steel', 'laptop', 'industrial', 'slim'],
  },
]
