import { createClient as createSupabaseClient, type SupabaseClient } from '@supabase/supabase-js'
import { requireAdmin } from './authorization'
import type { CatalogAttribute, CatalogCategory, CatalogConfiguration, CatalogRequirement, CatalogValueType } from '@/lib/catalog/configuration'

type AdminClient = SupabaseClient
export interface CategoryInput { name: string; slug: string; parentId?: string | null; description?: string | null; sortOrder?: number; isActive?: boolean }
export interface AttributeInput { name: string; slug: string; valueType: CatalogValueType; isRequired?: boolean; allowedValues?: string[]; validationRules?: Record<string, unknown>; categoryIds?: string[]; isActive?: boolean }
export interface RequirementInput { categoryId: string; fieldKey: string; label: string; isRequired?: boolean; validationRules?: Record<string, unknown>; sortOrder?: number; isActive?: boolean }

function db(): AdminClient { const url = process.env.NEXT_PUBLIC_SUPABASE_URL; const key = process.env.SUPABASE_SERVICE_ROLE_KEY; if (!url || !key) throw new Error('ADMIN_DATA_NOT_CONFIGURED'); return createSupabaseClient(url, key, { auth: { persistSession: false, autoRefreshToken: false } }) }
function text(value: unknown) { return typeof value === 'string' ? value : null }
function category(row: Record<string, unknown>): CatalogCategory { return { id: text(row.id) ?? '', parentId: text(row.parent_id), name: text(row.name) ?? '', slug: text(row.slug) ?? '', description: text(row.description), sortOrder: Number(row.sort_order ?? 0), isActive: row.is_active !== false, archivedAt: text(row.archived_at), createdAt: text(row.created_at) ?? '', updatedAt: text(row.updated_at) ?? '' } }
function attribute(row: Record<string, unknown>, categoryIds: string[]): CatalogAttribute { return { id: text(row.id) ?? '', name: text(row.name) ?? '', slug: text(row.slug) ?? '', valueType: (text(row.value_type) ?? 'text') as CatalogValueType, isRequired: row.is_required === true, allowedValues: Array.isArray(row.allowed_values) ? row.allowed_values.map(String) : [], validationRules: (row.validation_rules && typeof row.validation_rules === 'object' ? row.validation_rules : {}) as Record<string, unknown>, isActive: row.is_active !== false, categoryIds, createdAt: text(row.created_at) ?? '', updatedAt: text(row.updated_at) ?? '' } }
function requirement(row: Record<string, unknown>): CatalogRequirement { return { id: text(row.id) ?? '', categoryId: text(row.category_id) ?? '', fieldKey: text(row.field_key) ?? '', label: text(row.label) ?? '', isRequired: row.is_required !== false, validationRules: (row.validation_rules && typeof row.validation_rules === 'object' ? row.validation_rules : {}) as Record<string, unknown>, sortOrder: Number(row.sort_order ?? 0), isActive: row.is_active !== false, createdAt: text(row.created_at) ?? '', updatedAt: text(row.updated_at) ?? '' } }
async function audit(client: AdminClient, actorId: string, entityType: string, entityId: string | null, action: string, previousValue: unknown, newValue: unknown, reason?: string) { const { error } = await client.from('catalog_configuration_audit').insert({ actor_id: actorId, entity_type: entityType, entity_id: entityId, action, previous_value: previousValue, new_value: newValue, reason: reason ?? null }); if (error) throw new Error('AUDIT_WRITE_FAILED') }

export async function getCatalogConfiguration(): Promise<CatalogConfiguration> { const client = db(); const [{ data: categories, error: categoryError }, { data: attributes, error: attributeError }, { data: links, error: linkError }, { data: requirements, error: requirementError }] = await Promise.all([client.from('catalog_categories').select('*').order('sort_order'), client.from('catalog_attributes').select('*').order('name'), client.from('catalog_category_attributes').select('category_id, attribute_id'), client.from('catalog_requirements').select('*').order('sort_order')]); if (categoryError) throw categoryError; if (attributeError) throw attributeError; if (linkError) throw linkError; if (requirementError) throw requirementError; return { categories: (categories ?? []).map(category), attributes: (attributes ?? []).map((item) => attribute(item, (links ?? []).filter((link) => link.attribute_id === item.id).map((link) => link.category_id))), requirements: (requirements ?? []).map(requirement) } }

export async function listConfiguration() { await requireAdmin('manage_catalog_configuration'); return getCatalogConfiguration() }
export async function createCategory(input: CategoryInput) { const { user } = await requireAdmin('manage_catalog_configuration'); if (!input.name.trim() || !input.slug.trim()) throw new Error('INVALID_CATEGORY'); const client = db(); if (input.parentId === input.slug) throw new Error('CATEGORY_CYCLE'); const { data, error } = await client.from('catalog_categories').insert({ name: input.name.trim(), slug: input.slug.trim().toLowerCase(), parent_id: input.parentId ?? null, description: input.description?.trim() ?? null, sort_order: input.sortOrder ?? 0, is_active: input.isActive !== false }).select('*').single(); if (error) throw error; await audit(client, user.id, 'category', data.id, 'created', null, data); return category(data) }
export async function updateCategory(id: string, input: CategoryInput, reason?: string) { const { user } = await requireAdmin('manage_catalog_configuration'); const client = db(); const { data: current, error: lookupError } = await client.from('catalog_categories').select('*').eq('id', id).maybeSingle(); if (lookupError) throw lookupError; if (!current) throw new Error('CATEGORY_NOT_FOUND'); if (input.parentId === id) throw new Error('CATEGORY_CYCLE'); const { data, error } = await client.from('catalog_categories').update({ name: input.name.trim(), slug: input.slug.trim().toLowerCase(), parent_id: input.parentId ?? null, description: input.description?.trim() ?? null, sort_order: input.sortOrder ?? 0, is_active: input.isActive !== false, updated_at: new Date().toISOString() }).eq('id', id).select('*').single(); if (error) throw error; await audit(client, user.id, 'category', id, 'updated', current, data, reason); return category(data) }
export async function archiveCategory(id: string, reason?: string) { const { user } = await requireAdmin('manage_catalog_configuration'); const client = db(); const { data: current } = await client.from('catalog_categories').select('*').eq('id', id).maybeSingle(); if (!current) throw new Error('CATEGORY_NOT_FOUND'); const { data, error } = await client.from('catalog_categories').update({ is_active: false, archived_at: new Date().toISOString(), updated_at: new Date().toISOString() }).eq('id', id).select('*').single(); if (error) throw error; await audit(client, user.id, 'category', id, 'archived', current, data, reason); return category(data) }

export async function createAttribute(input: AttributeInput) { const { user } = await requireAdmin('manage_catalog_configuration'); if (!input.name.trim() || !input.slug.trim()) throw new Error('INVALID_ATTRIBUTE'); const client = db(); const { data, error } = await client.from('catalog_attributes').insert({ name: input.name.trim(), slug: input.slug.trim().toLowerCase(), value_type: input.valueType, is_required: input.isRequired === true, allowed_values: input.allowedValues ?? [], validation_rules: input.validationRules ?? {}, is_active: input.isActive !== false }).select('*').single(); if (error) throw error; if (input.categoryIds?.length) { const { error: linkError } = await client.from('catalog_category_attributes').insert(input.categoryIds.map((categoryId, index) => ({ category_id: categoryId, attribute_id: data.id, sort_order: index }))); if (linkError) throw linkError }; await audit(client, user.id, 'attribute', data.id, 'created', null, input); return data }
export async function updateAttribute(id: string, input: AttributeInput, reason?: string) { const { user } = await requireAdmin('manage_catalog_configuration'); const client = db(); const { data: current, error: lookupError } = await client.from('catalog_attributes').select('*').eq('id', id).maybeSingle(); if (lookupError) throw lookupError; if (!current) throw new Error('ATTRIBUTE_NOT_FOUND'); const { data, error } = await client.from('catalog_attributes').update({ name: input.name.trim(), slug: input.slug.trim().toLowerCase(), value_type: input.valueType, is_required: input.isRequired === true, allowed_values: input.allowedValues ?? [], validation_rules: input.validationRules ?? {}, is_active: input.isActive !== false, updated_at: new Date().toISOString() }).eq('id', id).select('*').single(); if (error) throw error; await client.from('catalog_category_attributes').delete().eq('attribute_id', id); if (input.categoryIds?.length) await client.from('catalog_category_attributes').insert(input.categoryIds.map((categoryId, index) => ({ category_id: categoryId, attribute_id: id, sort_order: index }))); await audit(client, user.id, 'attribute', id, 'updated', current, input, reason); return data }
export async function createRequirement(input: RequirementInput) { const { user } = await requireAdmin('manage_catalog_configuration'); if (!input.categoryId || !input.fieldKey.trim() || !input.label.trim()) throw new Error('INVALID_REQUIREMENT'); const client = db(); const { data, error } = await client.from('catalog_requirements').insert({ category_id: input.categoryId, field_key: input.fieldKey.trim(), label: input.label.trim(), is_required: input.isRequired !== false, validation_rules: input.validationRules ?? {}, sort_order: input.sortOrder ?? 0, is_active: input.isActive !== false }).select('*').single(); if (error) throw error; await audit(client, user.id, 'requirement', data.id, 'created', null, input); return requirement(data) }
export async function updateRequirement(id: string, input: RequirementInput, reason?: string) { const { user } = await requireAdmin('manage_catalog_configuration'); const client = db(); const { data: current, error: lookupError } = await client.from('catalog_requirements').select('*').eq('id', id).maybeSingle(); if (lookupError) throw lookupError; if (!current) throw new Error('REQUIREMENT_NOT_FOUND'); const { data, error } = await client.from('catalog_requirements').update({ category_id: input.categoryId, field_key: input.fieldKey.trim(), label: input.label.trim(), is_required: input.isRequired !== false, validation_rules: input.validationRules ?? {}, sort_order: input.sortOrder ?? 0, is_active: input.isActive !== false, updated_at: new Date().toISOString() }).eq('id', id).select('*').single(); if (error) throw error; await audit(client, user.id, 'requirement', id, 'updated', current, input, reason); return requirement(data) }
export async function archiveRequirement(id: string, reason?: string) { const { user } = await requireAdmin('manage_catalog_configuration'); const client = db(); const { data: current } = await client.from('catalog_requirements').select('*').eq('id', id).maybeSingle(); if (!current) throw new Error('REQUIREMENT_NOT_FOUND'); const { data, error } = await client.from('catalog_requirements').update({ is_active: false, updated_at: new Date().toISOString() }).eq('id', id).select('*').single(); if (error) throw error; await audit(client, user.id, 'requirement', id, 'deactivated', current, data, reason); return requirement(data) }
