import { createClient as createSupabaseClient, type SupabaseClient } from '@supabase/supabase-js'
import { requireAdmin, type AdminRole } from './authorization'
import { getCatalogConfiguration } from './catalog-configuration'

export const ADMIN_PRODUCT_STATUSES = ['draft', 'submitted', 'under_review', 'approved', 'rejected', 'published', 'inactive', 'archived'] as const
export type AdminProductStatus = typeof ADMIN_PRODUCT_STATUSES[number]
export type CatalogAction = 'approve' | 'reject' | 'request_changes' | 'disable' | 'reactivate' | 'archive'
export type CatalogSort = 'updated_desc' | 'created_desc' | 'price_asc' | 'price_desc' | 'name_asc'

export interface AdminProduct {
  id: string; vendorId: string; vendorName: string; name: string; sku: string; category: string; description: string; price: number; stock: number; status: AdminProductStatus; rawStatus: string; lifecycleStatus: string; createdAt: string; updatedAt: string; rejectionReason: string | null
}
export interface CatalogListResult { items: AdminProduct[]; total: number; page: number; pageSize: number; totalPages: number; role: AdminRole; categories: string[]; vendors: Array<{ id: string; name: string }> }
export interface CatalogDetail extends AdminProduct { approvalHistory: Array<{ id: string; status: string; comment: string | null; requestedChanges: string[]; changedBy: string | null; changedAt: string }>; changeHistory: Array<{ id: string; field: string; previousValue: unknown; newValue: unknown; reason: string | null; actorId: string; createdAt: string }> }
export interface ProductEditInput { name: string; sku: string; category: string; description: string; price: number; stock: number; reason: string }

type AdminClient = SupabaseClient
function db(): AdminClient { const url = process.env.NEXT_PUBLIC_SUPABASE_URL; const key = process.env.SUPABASE_SERVICE_ROLE_KEY; if (!url || !key) throw new Error('ADMIN_DATA_NOT_CONFIGURED'); return createSupabaseClient(url, key, { auth: { persistSession: false, autoRefreshToken: false } }) }
function text(row: Record<string, unknown>, key: string) { const value = row[key]; return typeof value === 'string' ? value : null }
function numberValue(row: Record<string, unknown>, key: string) { const value = row[key]; return typeof value === 'number' ? value : Number(value ?? 0) }
function statusOf(row: Record<string, unknown>): AdminProductStatus { const status = text(row, 'status') ?? 'draft'; const lifecycle = text(row, 'lifecycle_status') ?? 'inactive'; if (status === 'archived' || lifecycle === 'archived') return 'archived'; if (status === 'approved' && lifecycle === 'active') return 'published'; if (status === 'approved' && lifecycle === 'inactive') return 'inactive'; if (status === 'vendor_fix_required') return 'rejected'; return status as AdminProductStatus }
function mapProduct(row: Record<string, unknown>, vendorName: string): AdminProduct { return { id: text(row, 'id') ?? '', vendorId: text(row, 'vendor_id') ?? '', vendorName, name: text(row, 'name') ?? '', sku: text(row, 'sku') ?? '', category: text(row, 'category') ?? '', description: text(row, 'description') ?? '', price: numberValue(row, 'price'), stock: numberValue(row, 'stock'), status: statusOf(row), rawStatus: text(row, 'status') ?? 'draft', lifecycleStatus: text(row, 'lifecycle_status') ?? 'inactive', createdAt: text(row, 'created_at') ?? new Date(0).toISOString(), updatedAt: text(row, 'updated_at') ?? new Date(0).toISOString(), rejectionReason: text(row, 'rejection_reason') }
}
function rawStatusFilter(status: string): { status?: string; lifecycle?: string } { if (status === 'published') return { status: 'approved', lifecycle: 'active' }; if (status === 'inactive') return { status: 'approved', lifecycle: 'inactive' }; if (status === 'archived') return { lifecycle: 'archived' }; if (status === 'rejected') return { status: 'rejected' }; return { status } }
async function audit(client: AdminClient, actorId: string, productId: string, vendorId: string, action: string, metadata: Record<string, unknown>) { const { error } = await client.from('admin_audit_events').insert({ actor_id: actorId, action: `catalog.${action}`, entity_type: 'product', entity_id: productId, metadata: { ...metadata, vendorId } }); if (error) throw new Error('AUDIT_WRITE_FAILED') }

export async function listAdminProducts(input: { search?: string; sku?: string; vendorId?: string; category?: string; status?: string; createdFrom?: string; createdTo?: string; minPrice?: number; maxPrice?: number; sort?: CatalogSort; page?: number; pageSize?: number } = {}): Promise<CatalogListResult> {
  const { role } = await requireAdmin('review_products'); const client = db(); const pageSize = Math.min(50, Math.max(1, input.pageSize ?? 20)); const page = Math.max(1, input.page ?? 1)
  let query = client.from('vendor_products').select('*', { count: 'exact' }); if (input.vendorId) query = query.eq('vendor_id', input.vendorId); if (input.category) query = query.eq('category', input.category); if (input.sku?.trim()) query = query.ilike('sku', `%${input.sku.trim()}%`); if (input.search?.trim()) { const search = input.search.trim().replaceAll(',', ''); query = query.or(`name.ilike.%${search}%,sku.ilike.%${search}%,description.ilike.%${search}%`) }; if (input.createdFrom) query = query.gte('created_at', input.createdFrom); if (input.createdTo) query = query.lte('created_at', input.createdTo); if (input.minPrice !== undefined) query = query.gte('price', input.minPrice); if (input.maxPrice !== undefined) query = query.lte('price', input.maxPrice)
  const raw = rawStatusFilter(input.status ?? ''); if (raw.status) query = query.eq('status', raw.status); if (raw.lifecycle) query = query.eq('lifecycle_status', raw.lifecycle)
  const order: [string, boolean] = input.sort === 'price_asc' ? ['price', true] : input.sort === 'price_desc' ? ['price', false] : input.sort === 'name_asc' ? ['name', true] : input.sort === 'created_desc' ? ['created_at', false] : ['updated_at', false]; const { data, count, error } = await query.order(order[0], { ascending: order[1] })
  if (error) throw error
  const rows = data ?? []; const vendorIds = [...new Set(rows.map((row) => row.vendor_id))]; const [{ data: vendors }, { data: allProducts }] = await Promise.all([vendorIds.length ? client.from('profiles').select('id, full_name, email').in('id', vendorIds) : { data: [] }, client.from('vendor_products').select('category, vendor_id')])
  const vendorMap = new Map((vendors ?? []).map((vendor) => [vendor.id, vendor.full_name || vendor.email || 'Unnamed vendor'])); const items = rows.map((row) => mapProduct(row, vendorMap.get(row.vendor_id) ?? 'Unknown vendor')); const total = count ?? items.length; const totalPages = Math.max(1, Math.ceil(total / pageSize))
  return { items: items.slice((page - 1) * pageSize, page * pageSize), total, page, pageSize, totalPages, role, categories: [...new Set((allProducts ?? []).map((item) => item.category))].sort(), vendors: (vendors ?? []).map((vendor) => ({ id: vendor.id, name: vendor.full_name || vendor.email || 'Unnamed vendor' })) }
}

export async function getAdminProduct(productId: string): Promise<CatalogDetail> { await requireAdmin('review_products'); const client = db(); const [{ data: product, error }, { data: history }, { data: changes }] = await Promise.all([client.from('vendor_products').select('*').eq('id', productId).maybeSingle(), client.from('vendor_product_approval_events').select('id, status, comment, requested_changes, changed_by, changed_at').eq('product_id', productId).order('changed_at', { ascending: false }), client.from('admin_product_change_events').select('id, field_name, previous_value, new_value, reason, actor_id, created_at').eq('product_id', productId).order('created_at', { ascending: false })]); if (error) throw error; if (!product) throw new Error('PRODUCT_NOT_FOUND'); const { data: vendor } = await client.from('profiles').select('full_name, email').eq('id', product.vendor_id).maybeSingle(); return { ...mapProduct(product, vendor?.full_name || vendor?.email || 'Unknown vendor'), approvalHistory: (history ?? []).map((event) => ({ id: event.id, status: event.status, comment: event.comment, requestedChanges: event.requested_changes ?? [], changedBy: event.changed_by, changedAt: event.changed_at })), changeHistory: (changes ?? []).map((event) => ({ id: event.id, field: event.field_name, previousValue: event.previous_value, newValue: event.new_value, reason: event.reason, actorId: event.actor_id, createdAt: event.created_at })) } }

export async function moderateProduct(productId: string, action: CatalogAction, comment?: string) { const { user } = await requireAdmin('review_products'); if (['reject', 'request_changes', 'archive'].includes(action) && !comment?.trim()) throw new Error('REASON_REQUIRED'); const client = db(); const { data: product, error: lookupError } = await client.from('vendor_products').select('id, vendor_id, status, lifecycle_status').eq('id', productId).maybeSingle(); if (lookupError) throw lookupError; if (!product) throw new Error('PRODUCT_NOT_FOUND'); let update: Record<string, unknown>; if (action === 'approve') update = { status: 'approved', rejection_reason: null, updated_at: new Date().toISOString() }; else if (action === 'reject') update = { status: 'rejected', rejection_reason: comment?.trim(), is_active: false, lifecycle_status: 'inactive', updated_at: new Date().toISOString() }; else if (action === 'request_changes') update = { status: 'vendor_fix_required', rejection_reason: comment?.trim(), is_active: false, lifecycle_status: 'inactive', updated_at: new Date().toISOString() }; else if (action === 'disable') update = { lifecycle_status: 'inactive', is_active: false, updated_at: new Date().toISOString() }; else if (action === 'reactivate') { if (product.status !== 'approved') throw new Error('PRODUCT_NOT_APPROVED'); update = { lifecycle_status: 'active', is_active: true, updated_at: new Date().toISOString() } } else update = { status: 'archived', lifecycle_status: 'archived', is_active: false, archived_at: new Date().toISOString(), updated_at: new Date().toISOString() }; const { error } = await client.from('vendor_products').update(update).eq('id', productId); if (error) throw error; if (['approve', 'reject', 'request_changes'].includes(action)) await client.from('vendor_product_approval_events').insert({ product_id: productId, status: update.status, comment: comment?.trim() ?? null, requested_changes: action === 'request_changes' ? [comment?.trim()] : [], changed_by: user.id }); await audit(client, user.id, productId, product.vendor_id, action, { comment: comment?.trim() ?? null, previousStatus: product.status, previousLifecycle: product.lifecycle_status, next: update }); return { productId, action } }

export async function editAdminProduct(productId: string, input: ProductEditInput) {
  const { user } = await requireAdmin('review_products')
  if (!input.name.trim() || !input.sku.trim() || !input.category.trim() || !input.reason.trim() || !Number.isFinite(input.price) || input.price < 0 || !Number.isInteger(input.stock) || input.stock < 0) throw new Error('INVALID_PRODUCT_EDIT')
  const configuration = await getCatalogConfiguration()
  const category = configuration.categories.find((item) => item.name === input.category.trim() || item.slug === input.category.trim())
  if (!category || !category.isActive || category.archivedAt) throw new Error('INVALID_PRODUCT_CATEGORY')
  const client = db(); const { data: current, error: lookupError } = await client.from('vendor_products').select('*').eq('id', productId).maybeSingle()
  if (lookupError) throw lookupError; if (!current) throw new Error('PRODUCT_NOT_FOUND')
  const normalizedCategory = category.name
  const changes = [['name', current.name, input.name], ['sku', current.sku, input.sku], ['category', current.category, normalizedCategory], ['description', current.description, input.description], ['price', current.price, input.price], ['stock', current.stock, input.stock]].filter(([, previous, next]) => previous !== next)
  const { error } = await client.from('vendor_products').update({ name: input.name.trim(), sku: input.sku.trim(), category: normalizedCategory, description: input.description.trim(), price: input.price, stock: input.stock, updated_at: new Date().toISOString() }).eq('id', productId)
  if (error) throw error
  for (const [field, previousValue, newValue] of changes) await client.from('admin_product_change_events').insert({ product_id: productId, vendor_id: current.vendor_id, actor_id: user.id, field_name: field, previous_value: previousValue, new_value: newValue, reason: input.reason.trim() })
  await audit(client, user.id, productId, current.vendor_id, 'edited', { reason: input.reason.trim(), fields: changes.map(([field]) => field) }); return { productId, changedFields: changes.map(([field]) => field) }
}
