import { createClient as createSupabaseClient, type SupabaseClient } from '@supabase/supabase-js'
import { requireAdmin } from './authorization'
import { createBulkJob } from './bulk-operations'

type AdminClient = SupabaseClient
export type SupportStatus = 'open' | 'assigned' | 'in_progress' | 'waiting_on_vendor' | 'resolved' | 'closed'
export type SupportPriority = 'low' | 'medium' | 'high' | 'critical'
export interface AdminTicket { id: string; vendorId: string; vendorName: string; subject: string; category: string; priority: SupportPriority; status: SupportStatus; assignedTo: string | null; createdAt: string; updatedAt: string; messages: Array<{ id: string; authorType: string; body: string; authorId: string | null; createdAt: string }>; internalNotes: Array<{ id: string; body: string; authorId: string; createdAt: string }> }
function db(): AdminClient { const url = process.env.NEXT_PUBLIC_SUPABASE_URL; const key = process.env.SUPABASE_SERVICE_ROLE_KEY; if (!url || !key) throw new Error('ADMIN_DATA_NOT_CONFIGURED'); return createSupabaseClient(url, key, { auth: { persistSession: false, autoRefreshToken: false } }) }
async function audit(client: AdminClient, actorId: string, action: string, entityId: string, metadata: Record<string, unknown> = {}) { const { error } = await client.from('admin_audit_events').insert({ actor_id: actorId, action: `communication.${action}`, entity_type: 'support_or_notification', entity_id: entityId, metadata }); if (error) throw new Error('AUDIT_WRITE_FAILED') }
export async function listTickets(input: { vendorId?: string; status?: SupportStatus; priority?: SupportPriority; page?: number; pageSize?: number } = {}) { await requireAdmin('support.manage'); const client = db(); const size = Math.min(50, Math.max(1, input.pageSize ?? 20)); const page = Math.max(1, input.page ?? 1); let query = client.from('vendor_support_tickets').select('*', { count: 'exact' }); if (input.vendorId) query = query.eq('vendor_id', input.vendorId); if (input.status) query = query.eq('status', input.status); if (input.priority) query = query.eq('priority', input.priority); const { data: tickets, count, error } = await query.order('updated_at', { ascending: false }).range((page - 1) * size, page * size - 1); if (error) throw error; const ids = (tickets ?? []).map((ticket) => ticket.id); const vendors = [...new Set((tickets ?? []).map((ticket) => ticket.vendor_id))]; const [{ data: profiles }, { data: messages }] = await Promise.all([vendors.length ? client.from('profiles').select('id, full_name, email').in('id', vendors) : { data: [] }, ids.length ? client.from('vendor_support_messages').select('id, ticket_id, author_type, author_id, body, created_at').in('ticket_id', ids).order('created_at') : { data: [] }]); const names = new Map((profiles ?? []).map((profile) => [profile.id, profile.full_name || profile.email || 'Unnamed vendor'])); return { items: (tickets ?? []).map((ticket) => ({ id: ticket.id, vendorId: ticket.vendor_id, vendorName: names.get(ticket.vendor_id) ?? 'Unknown vendor', subject: ticket.subject, category: ticket.category, priority: ticket.priority, status: ticket.status, assignedTo: ticket.assigned_to, createdAt: ticket.created_at, updatedAt: ticket.updated_at, messages: (messages ?? []).filter((message) => message.ticket_id === ticket.id).map((message) => ({ id: message.id, authorType: message.author_type, authorId: message.author_id, body: message.body, createdAt: message.created_at })), internalNotes: [] })), total: count ?? 0, page, pageSize: size, totalPages: Math.max(1, Math.ceil((count ?? 0) / size)) } }
export async function updateTicket(ticketId: string, input: { status?: SupportStatus; priority?: SupportPriority; assignedTo?: string | null }) { const { user } = await requireAdmin('support.manage'); const client = db(); const { data: current, error: lookupError } = await client.from('vendor_support_tickets').select('*').eq('id', ticketId).maybeSingle(); if (lookupError) throw lookupError; if (!current) throw new Error('TICKET_NOT_FOUND'); const { error } = await client.from('vendor_support_tickets').update({ status: input.status ?? current.status, priority: input.priority ?? current.priority, assigned_to: input.assignedTo === undefined ? current.assigned_to : input.assignedTo, closed_at: input.status === 'closed' ? new Date().toISOString() : null, updated_at: new Date().toISOString() }).eq('id', ticketId); if (error) throw error; await audit(client, user.id, 'ticket_updated', ticketId, { previous: current, next: input }); return { ticketId, status: input.status ?? current.status, priority: input.priority ?? current.priority } }
export async function getTicket(ticketId: string) { await requireAdmin('support.manage'); const client = db(); const [{ data: ticket, error }, { data: messages }, { data: internalNotes }] = await Promise.all([client.from('vendor_support_tickets').select('*').eq('id', ticketId).maybeSingle(), client.from('vendor_support_messages').select('id, author_type, author_id, body, created_at').eq('ticket_id', ticketId).order('created_at'), client.from('vendor_support_internal_notes').select('id, author_id, body, created_at').eq('ticket_id', ticketId).order('created_at', { ascending: false })]); if (error) throw error; if (!ticket) throw new Error('TICKET_NOT_FOUND'); return { ...ticket, messages: messages ?? [], internalNotes: internalNotes ?? [] } }
export async function replyToTicket(ticketId: string, body: string) { const { user } = await requireAdmin('support.manage'); if (!body.trim()) throw new Error('MESSAGE_REQUIRED'); const client = db(); const { data: ticket } = await client.from('vendor_support_tickets').select('id, vendor_id').eq('id', ticketId).maybeSingle(); if (!ticket) throw new Error('TICKET_NOT_FOUND'); const { error } = await client.from('vendor_support_messages').insert({ ticket_id: ticketId, author_type: 'support', author_id: user.id, body: body.trim() }); if (error) throw error; await client.from('vendor_support_tickets').update({ status: 'in_progress', updated_at: new Date().toISOString() }).eq('id', ticketId); await audit(client, user.id, 'ticket_replied', ticketId, { vendorId: ticket.vendor_id }); return { ticketId } }
export async function addInternalNote(ticketId: string, body: string) { const { user } = await requireAdmin('support.manage'); if (!body.trim()) throw new Error('NOTE_REQUIRED'); const client = db(); const { data: ticket } = await client.from('vendor_support_tickets').select('id').eq('id', ticketId).maybeSingle(); if (!ticket) throw new Error('TICKET_NOT_FOUND'); const { error } = await client.from('vendor_support_internal_notes').insert({ ticket_id: ticketId, author_id: user.id, body: body.trim() }); if (error) throw error; await audit(client, user.id, 'internal_note_added', ticketId, {}); return { ticketId } }

export async function createCommunication(input: { audienceType: 'platform' | 'vendor' | 'vendor_group'; vendorIds?: string[]; title: string; body: string }) {
  const { user } = await requireAdmin('notifications.manage'); if (!input.title.trim() || !input.body.trim()) throw new Error('COMMUNICATION_REQUIRED'); if (input.audienceType === 'vendor' && input.vendorIds?.length !== 1) throw new Error('VENDOR_REQUIRED')
  const client = db(); let vendorIds = input.vendorIds ?? []
  if (input.audienceType === 'platform') { const { data, error } = await client.from('profiles').select('id').eq('role', 'vendor'); if (error) throw error; vendorIds = (data ?? []).map((item) => item.id) }
  const { data: communication, error } = await client.from('admin_communications').insert({ sender_id: user.id, audience_type: input.audienceType, vendor_id: input.audienceType === 'vendor' ? vendorIds[0] : null, title: input.title.trim(), body: input.body.trim() }).select('id').single(); if (error) throw error
  if (input.audienceType === 'platform' && vendorIds.length > 100) {
    const job = await createBulkJob({ operation: 'platform_announcement', entityIds: vendorIds, reason: `Platform announcement: ${input.title.trim()}`, payload: { title: input.title.trim(), body: input.body.trim(), communicationId: communication.id } })
    return { communicationId: communication.id, recipientCount: vendorIds.length, jobId: job.jobId, status: job.status }
  }
  for (const vendorId of vendorIds) { const { data: notification, error: notificationError } = await client.from('vendor_notifications').insert({ vendor_id: vendorId, type: 'announcement', title: input.title.trim(), body: input.body.trim() }).select('id').single(); if (notificationError) throw notificationError; const { error: recipientError } = await client.from('admin_communication_recipients').insert({ communication_id: communication.id, vendor_id: vendorId, notification_id: notification.id }); if (recipientError) throw recipientError }
  await audit(client, user.id, 'communication_sent', communication.id, { audienceType: input.audienceType, recipientCount: vendorIds.length }); return { communicationId: communication.id, recipientCount: vendorIds.length, status: 'completed' }
}
