import { createClient as createSupabaseClient, type SupabaseClient } from '@supabase/supabase-js'
import { requireAdmin } from './authorization'

type AdminClient = SupabaseClient
function db(): AdminClient { const url = process.env.NEXT_PUBLIC_SUPABASE_URL; const key = process.env.SUPABASE_SERVICE_ROLE_KEY; if (!url || !key) throw new Error('ADMIN_DATA_NOT_CONFIGURED'); return createSupabaseClient(url, key, { auth: { persistSession: false, autoRefreshToken: false } }) }
export async function listImports(page = 1, pageSize = 20) { await requireAdmin('review_imports'); const client = db(); const size = Math.min(50, Math.max(1, pageSize)); const { data, count, error } = await client.from('vendor_catalog_imports').select('*', { count: 'exact' }).order('uploaded_at', { ascending: false }).range((page - 1) * size, page * size - 1); if (error) throw error; return { items: data ?? [], total: count ?? 0, page, pageSize: size, totalPages: Math.max(1, Math.ceil((count ?? 0) / size)) } }
export async function getImport(importId: string) { await requireAdmin('review_imports'); const client = db(); const [{ data: record, error }, { data: errors }] = await Promise.all([client.from('vendor_catalog_imports').select('*').eq('id', importId).maybeSingle(), client.from('vendor_catalog_import_errors').select('*').eq('import_id', importId).order('row_number')]); if (error) throw error; if (!record) throw new Error('IMPORT_NOT_FOUND'); return { ...record, errors: errors ?? [] } }
export async function retryImport(importId: string) { const { user } = await requireAdmin('review_imports'); const client = db(); const { data: record, error } = await client.from('vendor_catalog_imports').select('*').eq('id', importId).maybeSingle(); if (error) throw error; if (!record) throw new Error('IMPORT_NOT_FOUND'); if (!['failed', 'validation_failed', 'completed_with_errors'].includes(record.status)) throw new Error('IMPORT_NOT_RETRYABLE'); const { error: updateError } = await client.from('vendor_catalog_imports').update({ status: 'ready_for_import', completed_at: null }).eq('id', importId); if (updateError) throw updateError; await client.from('admin_audit_events').insert({ actor_id: user.id, action: 'import.retry', entity_type: 'catalog_import', entity_id: importId, metadata: { previousStatus: record.status } }); return { importId, status: 'ready_for_import' } }
export async function errorReport(importId: string) { await requireAdmin('review_imports'); const client = db(); const { data: errors, error } = await client.from('vendor_catalog_import_errors').select('row_number, column_name, error_code, message, value').eq('import_id', importId).order('row_number'); if (error) throw error; const header = 'row,column,code,message,value'; const lines = (errors ?? []).map((item) => [item.row_number, item.column_name, item.error_code, item.message, item.value ?? ''].map((value) => JSON.stringify(value)).join(',')); return `${header}\n${lines.join('\n')}` }
