import { createClient as createSupabaseClient, type SupabaseClient } from '@supabase/supabase-js'
import { requireAdmin } from './authorization'

type AdminClient = SupabaseClient
export type ControlSource = 'vendor' | 'admin_override' | 'system'
export type ListingAction = 'activate' | 'deactivate' | 'archive'
export interface MarketplaceItem { id: string; vendorId: string; vendorName: string; productName: string; sku: string; price: number; stock: number; lowStock: boolean; outOfStock: boolean; rawPrice: number; rawStock: number; priceSource: ControlSource; inventorySource: ControlSource; lifecycleStatus: string; isActive: boolean; status: string; updatedAt: string }
export interface MarketplaceListResult { items: MarketplaceItem[]; total: number; page: number; pageSize: number; totalPages: number; vendors: Array<{ id: string; name: string }> }

function db(): AdminClient { const url = process.env.NEXT_PUBLIC_SUPABASE_URL; const key = process.env.SUPABASE_SERVICE_ROLE_KEY; if (!url || !key) throw new Error('ADMIN_DATA_NOT_CONFIGURED'); return createSupabaseClient(url, key, { auth: { persistSession: false, autoRefreshToken: false } }) }
function text(row: Record<string, unknown>, key: string) { const value = row[key]; return typeof value === 'string' ? value : null }
function numberValue(row: Record<string, unknown>, key: string) { const value = row[key]; return typeof value === 'number' ? value : Number(value ?? 0) }
function source(value: unknown): ControlSource { return value === 'admin_override' || value === 'system' ? value : 'vendor' }
function inventoryThreshold() { const value = Number(process.env.ADMIN_LOW_STOCK_THRESHOLD ?? 5); return Number.isFinite(value) && value >= 0 ? value : 5 }
function mapProduct(row: Record<string, unknown>, vendorName: string, latestInventory?: Record<string, unknown>, latestPrice?: Record<string, unknown>): MarketplaceItem { const rawStock = numberValue(row, 'stock'); const rawPrice = numberValue(row, 'price'); const stock = latestInventory ? numberValue(latestInventory, 'new_quantity') : rawStock; const price = latestPrice ? numberValue(latestPrice, 'new_price') : rawPrice; return { id: text(row, 'id') ?? '', vendorId: text(row, 'vendor_id') ?? '', vendorName, productName: text(row, 'name') ?? '', sku: text(row, 'sku') ?? '', price, stock, rawPrice, rawStock, lowStock: stock > 0 && stock <= inventoryThreshold(), outOfStock: stock <= 0, priceSource: latestPrice ? source(latestPrice.source) : 'vendor', inventorySource: latestInventory ? source(latestInventory.source) : 'vendor', lifecycleStatus: text(row, 'lifecycle_status') ?? 'inactive', isActive: row.is_active === true, status: text(row, 'status') ?? 'draft', updatedAt: text(row, 'updated_at') ?? new Date(0).toISOString() } }
async function audit(client: AdminClient, actorId: string, productId: string, vendorId: string, action: string, metadata: Record<string, unknown>) { const { error } = await client.from('admin_audit_events').insert({ actor_id: actorId, action: `marketplace.${action}`, entity_type: 'product', entity_id: productId, metadata: { ...metadata, vendorId } }); if (error) throw new Error('AUDIT_WRITE_FAILED') }

export async function listMarketplaceItems(input: { vendorId?: string; product?: string; lowStock?: boolean; outOfStock?: boolean; page?: number; pageSize?: number } = {}): Promise<MarketplaceListResult> { await requireAdmin('manage_inventory'); const client = db(); const pageSize = Math.min(50, Math.max(1, input.pageSize ?? 20)); const page = Math.max(1, input.page ?? 1); let query = client.from('vendor_products').select('*', { count: 'exact' }); if (input.vendorId) query = query.eq('vendor_id', input.vendorId); if (input.product?.trim()) { const search = input.product.trim().replaceAll(',', ''); query = query.or(`name.ilike.%${search}%,sku.ilike.%${search}%`) }; const { data, count, error } = await query.order('updated_at', { ascending: false }); if (error) throw error; const rows = data ?? []; const vendorIds = [...new Set(rows.map((row) => row.vendor_id))]; const [{ data: vendors }, { data: inventories }, { data: prices }] = await Promise.all([vendorIds.length ? client.from('profiles').select('id, full_name, email').in('id', vendorIds) : { data: [] }, client.from('inventory_adjustment_events').select('*').in('product_id', rows.map((row) => row.id)).order('created_at', { ascending: false }), client.from('price_adjustment_events').select('*').in('product_id', rows.map((row) => row.id)).order('created_at', { ascending: false })]); const vendorMap = new Map((vendors ?? []).map((vendor) => [vendor.id, vendor.full_name || vendor.email || 'Unnamed vendor'])); const inventoryMap = new Map<string, Record<string, unknown>>(); for (const item of inventories ?? []) if (!inventoryMap.has(item.product_id)) inventoryMap.set(item.product_id, item); const priceMap = new Map<string, Record<string, unknown>>(); for (const item of prices ?? []) if (!priceMap.has(item.product_id)) priceMap.set(item.product_id, item); let items = rows.map((row) => mapProduct(row, vendorMap.get(row.vendor_id) ?? 'Unknown vendor', inventoryMap.get(row.id), priceMap.get(row.id))); if (input.lowStock) items = items.filter((item) => item.lowStock); if (input.outOfStock) items = items.filter((item) => item.outOfStock); const total = count ?? items.length; const totalPages = Math.max(1, Math.ceil(total / pageSize)); return { items: items.slice((page - 1) * pageSize, page * pageSize), total, page, pageSize, totalPages, vendors: (vendors ?? []).map((vendor) => ({ id: vendor.id, name: vendor.full_name || vendor.email || 'Unnamed vendor' })) } }

export async function adjustInventory(productId: string, quantity: number, reason: string) { const { user } = await requireAdmin('manage_inventory'); if (!Number.isInteger(quantity) || quantity < 0 || !reason.trim()) throw new Error('INVALID_INVENTORY_ADJUSTMENT'); const client = db(); const { data: product, error } = await client.from('vendor_products').select('id, vendor_id, stock').eq('id', productId).maybeSingle(); if (error) throw error; if (!product) throw new Error('PRODUCT_NOT_FOUND'); const { error: updateError } = await client.from('vendor_products').update({ stock: quantity, updated_at: new Date().toISOString() }).eq('id', productId); if (updateError) throw updateError; await client.from('inventory_adjustment_events').insert({ product_id: productId, vendor_id: product.vendor_id, source: 'admin_override', actor_id: user.id, previous_quantity: product.stock, new_quantity: quantity, reason: reason.trim() }); await audit(client, user.id, productId, product.vendor_id, 'inventory_override', { previous: product.stock, next: quantity, reason: reason.trim(), source: 'admin_override' }); return { productId, quantity, source: 'admin_override' } }

export async function adjustPrice(productId: string, price: number, reason: string) { const { user } = await requireAdmin('manage_pricing'); if (!Number.isFinite(price) || price < 0 || !reason.trim()) throw new Error('INVALID_PRICE_ADJUSTMENT'); const client = db(); const { data: product, error } = await client.from('vendor_products').select('id, vendor_id, price').eq('id', productId).maybeSingle(); if (error) throw error; if (!product) throw new Error('PRODUCT_NOT_FOUND'); const { error: updateError } = await client.from('vendor_products').update({ price, updated_at: new Date().toISOString() }).eq('id', productId); if (updateError) throw updateError; await client.from('price_adjustment_events').insert({ product_id: productId, vendor_id: product.vendor_id, source: 'admin_override', actor_id: user.id, previous_price: product.price, new_price: price, reason: reason.trim() }); await audit(client, user.id, productId, product.vendor_id, 'price_override', { previous: product.price, next: price, reason: reason.trim(), source: 'admin_override' }); return { productId, price, source: 'admin_override' } }

export async function bulkAdjustPrice(productIds: string[], price: number, reason: string) { const { user } = await requireAdmin('manage_pricing'); if (!productIds.length || !Number.isFinite(price) || price < 0 || !reason.trim()) throw new Error('INVALID_PRICE_ADJUSTMENT'); const client = db(); const { data: products, error } = await client.from('vendor_products').select('id, vendor_id, price').in('id', productIds); if (error) throw error; for (const product of products ?? []) { await client.from('vendor_products').update({ price, updated_at: new Date().toISOString() }).eq('id', product.id); await client.from('price_adjustment_events').insert({ product_id: product.id, vendor_id: product.vendor_id, source: 'admin_override', actor_id: user.id, previous_price: product.price, new_price: price, reason: reason.trim() }); await audit(client, user.id, product.id, product.vendor_id, 'bulk_price_override', { previous: product.price, next: price, reason: reason.trim(), source: 'admin_override' }) } return { updated: products?.length ?? 0, price, source: 'admin_override' } }

export async function changeListing(productId: string, action: ListingAction, reason?: string) { const { user } = await requireAdmin('manage_marketplace'); const trimmedReason = reason?.trim() ?? ''; if (['deactivate', 'activate'].includes(action) && !trimmedReason) throw new Error('REASON_REQUIRED'); const client = db(); const { data: product, error } = await client.from('vendor_products').select('id, vendor_id, status, lifecycle_status, is_active').eq('id', productId).maybeSingle(); if (error) throw error; if (!product) throw new Error('PRODUCT_NOT_FOUND'); if (action !== 'archive' && product.status !== 'approved') throw new Error('PRODUCT_NOT_APPROVED'); const update = action === 'activate' ? { lifecycle_status: 'active', is_active: true } : action === 'deactivate' ? { lifecycle_status: 'inactive', is_active: false } : { lifecycle_status: 'archived', is_active: false, archived_at: new Date().toISOString() }; const { error: updateError } = await client.from('vendor_products').update({ ...update, updated_at: new Date().toISOString() }).eq('id', productId); if (updateError) throw updateError; await audit(client, user.id, productId, product.vendor_id, `listing_${action}`, { previousLifecycle: product.lifecycle_status, nextLifecycle: update.lifecycle_status, reason: trimmedReason || null, source: 'admin_override' }); return { productId, action, source: 'admin_override' } }

export async function scheduleListing(productId: string, action: 'activate' | 'deactivate', executeAt: string) { const { user } = await requireAdmin('manage_marketplace'); const when = new Date(executeAt); if (Number.isNaN(when.getTime()) || when <= new Date()) throw new Error('INVALID_SCHEDULE'); const client = db(); const { data: product, error } = await client.from('vendor_products').select('id, vendor_id, status').eq('id', productId).maybeSingle(); if (error) throw error; if (!product) throw new Error('PRODUCT_NOT_FOUND'); if (product.status !== 'approved') throw new Error('PRODUCT_NOT_APPROVED'); const { data, error: scheduleError } = await client.from('marketplace_listing_schedules').insert({ product_id: productId, vendor_id: product.vendor_id, action, execute_at: when.toISOString(), created_by: user.id }).select('*').single(); if (scheduleError) throw scheduleError; await audit(client, user.id, productId, product.vendor_id, 'listing_scheduled', { action, executeAt: when.toISOString(), source: 'admin_override' }); return data }
