'use client'

import Link from 'next/link'
import { useCallback, useEffect, useState } from 'react'
import type { OnboardingListResult, OnboardingVendor } from '@/lib/admin/onboarding'

function label(value: string) { return value.replaceAll('_', ' ') }
function formatDate(value: string) { return new Intl.DateTimeFormat('en', { month: 'short', day: 'numeric', year: 'numeric' }).format(new Date(value)) }

export function OnboardingWorkspace() {
  const [result, setResult] = useState<OnboardingListResult | null>(null); const [search, setSearch] = useState(''); const [status, setStatus] = useState(''); const [page, setPage] = useState(1); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  const load = useCallback(async () => { setLoading(true); try { const params = new URLSearchParams({ search, status, page: String(page), pageSize: '20' }); const response = await fetch(`/api/admin/onboarding?${params}`); const data = await response.json() as OnboardingListResult & { error?: string }; if (!response.ok) throw new Error(data.error || 'Unable to load onboarding.'); setResult(data); setError('') } catch (loadError) { setError(loadError instanceof Error ? loadError.message : 'Unable to load onboarding.') } finally { setLoading(false) } }, [page, search, status])
  useEffect(() => { void load() }, [load])
  return <main className="admin-page"><header className="admin-header"><Link href="/admin" className="logo logo-active">Furnish<span>AI</span></Link><nav><Link href="/admin" className="admin-nav-link">Dashboard</Link><Link href="/admin/vendors" className="admin-nav-link">Vendors</Link><span className="admin-role-chip">Onboarding review</span></nav></header><div className="admin-shell"><section className="admin-hero admin-hero-compact"><div><p className="admin-eyebrow">Admin portal / Phase 03</p><h1>Onboarding review.</h1><p>Verify the business profile and required documents before a vendor becomes active.</p></div></section><section className="admin-filter-bar" aria-label="Onboarding filters"><label><span>Search</span><input value={search} onChange={(event) => { setPage(1); setSearch(event.target.value) }} placeholder="Company or legal name" /></label><label><span>Onboarding status</span><select value={status} onChange={(event) => { setPage(1); setStatus(event.target.value) }}><option value="">Pending and recent</option><option value="submitted">Submitted</option><option value="action_required">Action required</option><option value="in_progress">In progress</option><option value="rejected">Rejected</option></select></label></section>{error ? <div className="admin-config-notice admin-config-error" role="alert">{error}</div> : null}<section className="admin-panel admin-vendor-table-panel"><div className="admin-panel-heading"><div><p className="admin-eyebrow">Review queue</p><h2>{result ? `${result.total} onboarding records` : 'Onboarding records'}</h2></div><span className="admin-data-note">Private documents</span></div>{loading ? <p className="admin-empty" role="status">Loading onboarding records...</p> : result?.items.length ? <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Vendor</th><th>Onboarding</th><th>Progress</th><th>Documents</th><th>Updated</th><th /></tr></thead><tbody>{result.items.map((vendor) => <OnboardingRow vendor={vendor} key={vendor.id} />)}</tbody></table></div> : <p className="admin-empty">No onboarding records match the current filters.</p>}<div className="admin-pagination"><button type="button" className="admin-button admin-button-secondary" disabled={!result || page <= 1} onClick={() => setPage((current) => current - 1)}>Previous</button><span>{result ? `Page ${result.page} of ${result.totalPages}` : 'Page —'}</span><button type="button" className="admin-button admin-button-secondary" disabled={!result || page >= result.totalPages} onClick={() => setPage((current) => current + 1)}>Next</button></div></section></div></main>
}

function OnboardingRow({ vendor }: { vendor: OnboardingVendor }) { return <tr><td><Link href={`/admin/onboarding/${vendor.id}`} className="admin-table-primary">{vendor.name}</Link><span className="admin-table-secondary">{vendor.email || 'No email'}</span></td><td><span className={`admin-status admin-status-${vendor.onboardingStatus}`}>{label(vendor.onboardingStatus)}</span></td><td><strong>{vendor.progress}%</strong></td><td>{vendor.documentsTotal - vendor.documentsPending}/{vendor.documentsTotal} approved</td><td>{formatDate(vendor.updatedAt)}</td><td><Link href={`/admin/onboarding/${vendor.id}`} className="admin-text-link">Review</Link></td></tr> }
